In [2]:
import numpy as np
import pandas as pd

In [3]:
df1=pd.DataFrame({"A":[1,2],"B":[3,4]})
df2=pd.DataFrame({"A":[5,7],"B":[7,9]})

In [4]:
df1

   A  B
0  1  3
1  2  4

In [5]:
df2

   A  B
0  5  7
1  7  9

# Rule for Concat ==> no of entries same and name of columns same

In [6]:
pd.concat((df1,df2))

   A  B
0  1  3
1  2  4
0  5  7
1  7  9

In [7]:
pd.concat((df1,df2),axis=0)  
#  row concatenation

   A  B
0  1  3
1  2  4
0  5  7
1  7  9

In [8]:
pd.concat((df1,df2),axis=1)
#  column concatenation

   A  B  A  B
0  1  3  5  7
1  2  4  7  9

In [9]:
df1=pd.DataFrame({"A":[1,2],"B":[3,4]})
df2=pd.DataFrame({"C":[5,7],"B":[7,9]})

In [10]:
pd.concat((df1,df2))

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  7  5.0
1  NaN  9  7.0

In [11]:
df1=pd.DataFrame({"A":[1,2],"B":[3,4]})
df2=pd.DataFrame({"C":[5,7],"D":[7,9]})

In [12]:
pd.concat((df1,df2))

     A    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  7.0  9.0

In [13]:
pd.concat((df1,df2),axis=1)

   A  B  C  D
0  1  3  5  7
1  2  4  7  9

In [16]:
df1=pd.DataFrame({"A":[1,2],"B":[3,4]})
df2=pd.DataFrame({"C":[5,7,9],"D":[7,91,2]}) 
#  in df2 like in same datframe give same no of entry

In [17]:
pd.concat((df1,df2),axis=1)

     A    B  C   D
0  1.0  3.0  5   7
1  2.0  4.0  7  91
2  NaN  NaN  9   2

In [18]:
df1=pd.DataFrame({"A":[1,2],"B":[3,4]})
df2=pd.DataFrame({"A":[5,7],"B":[7,9]})

In [19]:
pd.concat((df1,df2))

   A  B
0  1  3
1  2  4
0  5  7
1  7  9

In [20]:
pd.concat((df1,df2),ignore_index=True)

   A  B
0  1  3
1  2  4
2  5  7
3  7  9

In [21]:
pd.concat((df1,df2),ignore_index=False)  
# ignore_index ==> False by default

   A  B
0  1  3
1  2  4
0  5  7
1  7  9

In [23]:
pd.concat((df1,df2),ignore_index=False,keys=["A1","B1"])

      A  B
A1 0  1  3
   1  2  4
B1 0  5  7
   1  7  9

In [24]:
pd.concat((df1,df2),ignore_index=False,keys=["C","D"])

     A  B
C 0  1  3
  1  2  4
D 0  5  7
  1  7  9

# inner join gives common 
# while outer join gives all data

In [27]:
df1=pd.DataFrame({"A":[1,2],"B":[3,4]})
df2=pd.DataFrame({"C":[5,7],"B":[7,9]})

In [28]:
pd.concat((df1,df2),join="inner")

   B
0  3
1  4
0  7
1  9

In [29]:
pd.concat((df1,df2),join="outer")

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  7  5.0
1  NaN  9  7.0

In [30]:
df1=pd.DataFrame({"B":[1,2],"A":[3,4]})
df2=pd.DataFrame({"C":[5,7],"B":[7,9]})

In [31]:
pd.concat((df1,df2),join="inner")

   B
0  1
1  2
0  7
1  9

In [32]:
pd.concat((df1,df2),join="outer")

   B    A    C
0  1  3.0  NaN
1  2  4.0  NaN
0  7  NaN  5.0
1  9  NaN  7.0

In [33]:
pd.concat((df1,df2),join="outer",sort=True)

     A  B    C
0  3.0  1  NaN
1  4.0  2  NaN
0  NaN  7  5.0
1  NaN  9  7.0

# concat & join 3M or MCQ

In [46]:
df1=pd.DataFrame({"sub":["FSD","Python","DM"],"fac":["nas","vha","mss"],"id":[1,2,4]})
df2=pd.DataFrame({"id":[1,2,3],"mark":[9,10,8]})

In [47]:
df1

      sub  fac  id
0     FSD  nas   1
1  Python  vha   2
2      DM  mss   4

In [48]:
df2

   id  mark
0   1     9
1   2    10
2   3     8

# for merge one column same is the requirement

In [49]:
pd.merge(df1,df2)

      sub  fac  id  mark
0     FSD  nas   1     9
1  Python  vha   2    10

In [50]:
pd.merge(df1,df2,on="id")

      sub  fac  id  mark
0     FSD  nas   1     9
1  Python  vha   2    10

In [51]:
pd.merge(df1,df2,on="id",how="inner")

      sub  fac  id  mark
0     FSD  nas   1     9
1  Python  vha   2    10

In [52]:
pd.merge(df1,df2,on="id",how="outer")

      sub  fac  id  mark
0     FSD  nas   1   9.0
1  Python  vha   2  10.0
2      DM  mss   4   NaN
3     NaN  NaN   3   8.0

In [53]:
df1.merge(df2,on="id")

      sub  fac  id  mark
0     FSD  nas   1     9
1  Python  vha   2    10

# In terms of sql df1 ==> left table and df2 ==> right table

In [57]:
df1.merge(df2,on="id",how="left")

      sub  fac  id  mark
0     FSD  nas   1   9.0
1  Python  vha   2  10.0
2      DM  mss   4   NaN

In [58]:
df1.merge(df2,on="id",how="right")

      sub  fac  id  mark
0     FSD  nas   1     9
1  Python  vha   2    10
2     NaN  NaN   3     8

In [61]:
df1.merge(df2,how="cross")  
#  how ==> cross gives possible combination , will work in other version
# student table and subject table ma common subject ave ena mate use karvanu cross

KeyError: 'cross'

In [62]:
df1=pd.DataFrame({"sub":["FSD","Python","DM"],"fac":["nas","vha","mss"],"id_x":[1,2,4]})
df2=pd.DataFrame({"id_v":[1,2,3],"mark":[9,10,8]})

In [64]:
df1.merge(df2,left_on="id_x",right_on="id_v")

      sub  fac  id_x  id_v  mark
0     FSD  nas     1     1     9
1  Python  vha     2     2    10

In [65]:
df1.merge(df2,left_on="id_x",right_on="id_v",left_index=True,right_index=True)
# banne ma same index hovi joi ae

      sub  fac  id_x  id_v  mark
0     FSD  nas     1     1     9
1  Python  vha     2     2    10
2      DM  mss     4     3     8

In [67]:
df1=pd.DataFrame({"sub":["FSD","Python","DM"],"fac":["nas","vha","mss"],"id_x":[1,2,4]})
df2=pd.DataFrame({"id_v":[1,2,3],"mark":[9,10,8],"fac":["nas","vha","mss"]})

In [68]:
df1.merge(df2,left_on="id_x",right_on="id_v")

#  just fac mate suffix lagi jase by dafault vadu if u want to change suffix refer down cell

      sub fac_x  id_x  id_v  mark fac_y
0     FSD   nas     1     1     9   nas
1  Python   vha     2     2    10   vha

In [69]:
df1.merge(df2,left_on="id_x",right_on="id_v",suffixes=["_df1","_df2"])

      sub fac_df1  id_x  id_v  mark fac_df2
0     FSD     nas     1     1     9     nas
1  Python     vha     2     2    10     vha

In [70]:
df1.merge(df2,left_on="id_x",right_on="id_v",suffixes=["_df1","_df1"])
# this wont give error but will give same name to both

      sub fac_df1  id_x  id_v  mark fac_df1
0     FSD     nas     1     1     9     nas
1  Python     vha     2     2    10     vha