In [8]:
import pandas as pd
df=pd.read_csv("social_media_engagement.csv")

In [9]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [10]:
df.head()

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive

In [11]:
df.tail()

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   post_id          100 non-null    int64
 1   platform         100 non-null    object
 2   post_type        100 non-null    object
 3   post_time        100 non-null    object
 4   likes            100 non-null    int64
 5   comments         100 non-null    int64
 6   shares           100 non-null    int64
 7   post_day         100 non-null    object
 8   sentiment_score  100 non-null    object
dtypes: int64(4), object(5)
memory usage: 7.2+ KB

In [15]:
df.isna().sum()

post_id            0
platform           0
post_type          0
post_time          0
likes              0
comments           0
shares             0
post_day           0
sentiment_score    0
dtype: int64

In [17]:
df.dtypes

post_id             int64
platform           object
post_type          object
post_time          object
likes               int64
comments            int64
shares              int64
post_day           object
sentiment_score    object
dtype: object

In [18]:
df.nunique()

post_id            100
platform             3
post_type            5
post_time           99
likes               93
comments            85
shares              96
post_day             7
sentiment_score      3
dtype: int64

In [19]:
df.columns

Index(['post_id', 'platform', 'post_type', 'post_time', 'likes', 'comments',
       'shares', 'post_day', 'sentiment_score'],
      dtype='object')

In [21]:
df.platform.unique()

array(['Facebook', 'Instagram', 'Twitter'], dtype=object)

In [22]:
df.post_type.unique()

array(['image', 'carousel', 'poll', 'video', 'text'], dtype=object)

In [23]:
df.sentiment_score.unique()

array(['positive', 'neutral', 'negative'], dtype=object)

In [31]:
df.platform

0      Facebook
1      Facebook
2     Instagram
3       Twitter
4       Twitter
        ...
95    Instagram
96      Twitter
97      Twitter
98    Instagram
99    Instagram
Name: platform, Length: 100, dtype: object

In [74]:

df.groupby("platform")["likes"].sum()

platform
Facebook      86392
Instagram    107994
Twitter       43795
Name: likes, dtype: int64

In [ ]:
df.groupby("platform")["likes"].sum()

In [39]:
df.groupby("platform")[["likes","comments","shares"]].sum()

            likes  comments  shares
platform
Facebook    86392      7965   15180
Instagram  107994      8368   18906
Twitter     43795      3933    7479

In [43]:
# (lambda x: y= df.groupby("platform")["likes"].sum() if y<50000 x="v.good" else x="good")

SyntaxError: invalid syntax (<ipython-input-43-cf01a9fd116b>, line 1)

In [45]:
x=df.groupby("platform")["likes"].sum().apply(lambda x: "good" if x>50000 else "v.good")

In [46]:
x

platform
Facebook       good
Instagram      good
Twitter      v.good
Name: likes, dtype: object

In [47]:
df.groupby("platform").head()

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
5,6,Instagram,carousel,5/5/2023 20:00,256,186,211,Friday,neutral
6,7,Instagram,image,2/26/2023 11:45,1982,30,906,Sunday,positive
7,8,Instagram,text,10/28/2023 19:30,1274,45,216,Saturday,neutral
8,9,Facebook,video,5/2/2023 6:15,317,249,221,Tuesday,neutral
9,10,Twitter,carousel,5/11/2023 11:00,1878,225,438,Thursday,neutral
10,11,Twitter,text,12/8/2023 2:15,1446,44,52,Friday,negative
11,12,Twitter,video,6/15/2023 3:15,304,42,89,Thursday,positive
12,13,Facebook,carousel,11/11/2023 15:45,45,78,375,Saturday,negative
14,15,Facebook,carousel,1/9/2023 20:00,889,314,262,Monday,positive
16,17,Instagram,poll,7/5/2023 5:15,2872,10,736,Wednesday,positive

In [48]:
df.groupby("platform").tail()

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
76,77,Twitter,carousel,7/5/2023 18:15,3571,102,96,Wednesday,positive
84,85,Facebook,text,7/6/2023 7:00,2566,368,304,Thursday,neutral
85,86,Twitter,text,11/25/2023 7:30,2416,50,62,Saturday,positive
87,88,Facebook,text,5/3/2023 12:30,3404,244,67,Wednesday,positive
88,89,Twitter,carousel,5/3/2023 8:00,2884,197,339,Wednesday,positive
90,91,Facebook,carousel,9/15/2023 0:45,3956,402,462,Friday,negative
91,92,Facebook,video,2/23/2023 17:15,1857,216,344,Thursday,positive
92,93,Instagram,carousel,5/7/2023 0:30,951,432,734,Sunday,negative
93,94,Facebook,image,11/27/2023 4:30,1694,207,290,Monday,positive
94,95,Instagram,poll,3/7/2023 19:15,3005,124,517,Tuesday,positive
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [49]:
df.groupby("platform").sample()

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
12,13,Facebook,carousel,11/11/2023 15:45,45,78,375,Saturday,negative
23,24,Instagram,carousel,1/1/2023 20:00,5000,80,399,Sunday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral

In [51]:
df.groupby("platform").describe()

          post_id                                                       likes  \
            count       mean        std  min    25%   50%    75%    max count
platform
Facebook     32.0  51.531250  29.195652  1.0  28.75  53.0  76.25   94.0  32.0
Instagram    36.0  57.472222  28.866675  3.0  38.75  60.5  79.75  100.0  36.0
Twitter      32.0  41.625000  27.492814  4.0  18.75  39.5  56.00   98.0  32.0

                        ... comments        shares                          \
                  mean  ...      75%    max  count        mean         std
platform                ...
Facebook   2699.750000  ...   393.00  500.0   32.0  474.375000  299.739430
Instagram  2999.833333  ...   339.00  500.0   36.0  525.166667  284.467472
Twitter    1368.593750  ...   162.25  247.0   32.0  233.718750  156.508525


            min     25%    50%     75%    max
platform
Facebook   16.0  283.00  408.5  728.75  993.0
Instagram  25.0  226.50  573.5  758.00  956.0
Twitter    18.0   94.25  217.0  341.25  496.0

[3 rows x 32 columns]

In [52]:
df.groupby("platform").describe().sum()

post_id   count      100.000000
          mean       150.628472
          std         85.555141
          min          8.000000
          25%         86.250000
          50%        153.000000
          75%        212.000000
          max        292.000000
likes     count      100.000000
          mean      7068.177083
          std       4327.125298
          min        179.000000
          25%       3653.500000
          50%       6868.000000
          75%      10936.750000
          max      13571.000000
comments  count      100.000000
          mean       604.256944
          std        358.166283
          min         55.000000
          25%        296.000000
          50%        562.000000
          75%        894.250000
          max       1247.000000
shares    count      100.000000
          mean      1233.260417
          std        740.715427
          min         59.000000
          25%        603.750000
          50%       1199.000000
          75%       1828.000000
          max       2445.000000
dtype: float64

In [53]:
df.groupby("platform").describe().mean()

post_id   count      33.333333
          mean       50.209491
          std        28.518380
          min         2.666667
          25%        28.750000
          50%        51.000000
          75%        70.666667
          max        97.333333
likes     count      33.333333
          mean     2356.059028
          std      1442.375099
          min        59.666667
          25%      1217.833333
          50%      2289.333333
          75%      3645.583333
          max      4523.666667
comments  count      33.333333
          mean      201.418981
          std       119.388761
          min        18.333333
          25%        98.666667
          50%       187.333333
          75%       298.083333
          max       415.666667
shares    count      33.333333
          mean      411.086806
          std       246.905142
          min        19.666667
          25%       201.250000
          50%       399.666667
          75%       609.333333
          max       815.000000
dtype: float64

In [54]:
df.groupby("platform").describe().value_counts()

(post_id, count)  (post_id, mean)  (post_id, std)  (post_id, min)  (post_id, 25%)  (post_id, 50%)  (post_id, 75%)  (post_id, max)  (likes, count)  (likes, mean)  (likes, std)  (likes, min)  (likes, 25%)  (likes, 50%)  (likes, 75%)  (likes, max)  (comments, count)  (comments, mean)  (comments, std)  (comments, min)  (comments, 25%)  (comments, 50%)  (comments, 75%)  (comments, max)  (shares, count)  (shares, mean)  (shares, std)  (shares, min)  (shares, 25%)  (shares, 50%)  (shares, 75%)  (shares, max)
32.0              41.625000        27.492814       4.0             18.75           39.5            56.00           98.0            32.0            1368.593750    1020.364257   119.0         470.0         1225.5        2240.25       3571.0        32.0               122.906250        55.063810        34.0             89.75            122.5            162.25           247.0            32.0             233.718750      156.508525     18.0           94.25          217.0          341.25         496.0            1
                  51.531250        29.195652       1.0             28.75           53.0            76.25           94.0            32.0            2699.750000    1579.812014   45.0          1693.0        2415.5        4028.25       5000.0        32.0               248.906250        159.074411       11.0             86.00            238.0            393.00           500.0            32.0             474.375000      299.739430     16.0           283.00         408.5          728.75         993.0            1
36.0              57.472222        28.866675       3.0             38.75           60.5            79.75           100.0           36.0            2999.833333    1726.949027   15.0          1490.5        3227.0        4668.25       5000.0        36.0               232.444444        144.028062       10.0             120.25           201.5            339.00           500.0            36.0             525.166667      284.467472     25.0           226.50         573.5          758.00         956.0            1
Name: count, dtype: int64

In [55]:
df.groupby("platform").size()

platform
Facebook     32
Instagram    36
Twitter      32
dtype: int64

In [56]:
df.shape

(100, 9)

In [57]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [58]:
df.groupby("platform").groups

{'Facebook': [0, 1, 8, 12, 14, 19, 25, 27, 28, 29, 30, 35, 36, 38, 46, 47, 57, 61, 65, 66, 69, 71, 72, 74, 79, 80, 83, 84, 87, 90, 91, 93], 'Instagram': [2, 5, 6, 7, 16, 23, 26, 31, 34, 39, 41, 43, 45, 49, 53, 55, 56, 59, 60, 63, 64, 67, 70, 73, 75, 77, 78, 81, 82, 86, 89, 92, 94, 95, 98, 99], 'Twitter': [3, 4, 9, 10, 11, 13, 15, 17, 18, 20, 21, 22, 24, 32, 33, 37, 40, 42, 44, 48, 50, 51, 52, 54, 58, 62, 68, 76, 85, 88, 96, 97]}

In [60]:
for i,j in df.groupby("platform"):
    print(i,"name")
    print(j,"data")

Facebook name
    post_id  platform post_type         post_time  likes  comments  shares  \
0         1  Facebook     image   8/17/2023 14:45   2121       474     628
1         2  Facebook  carousel    5/14/2023 0:45   3660       432     694
8         9  Facebook     video     5/2/2023 6:15    317       249     221
12       13  Facebook  carousel  11/11/2023 15:45     45        78     375
14       15  Facebook  carousel    1/9/2023 20:00    889       314     262
19       20  Facebook     image    2/2/2023 16:00    455        86      79
25       26  Facebook  carousel    10/5/2023 6:30   1992        70     515
27       28  Facebook      poll     3/1/2023 8:00   2083       500     388
28       29  Facebook     image    1/7/2023 10:30    548       153     731
29       30  Facebook  carousel     2/3/2023 0:30   4594       216     739
30       31  Facebook      poll   9/10/2023 13:45   4795       449     978
35       36  Facebook     video    4/8/2023 19:15   5000       500      43
36       37  Facebook     video    5/11/2023 0:30   4245        59      83
38       39  Facebook     video     1/1/2023 6:00   5000       430     980
46       47  Facebook      poll    8/8/2023 17:45   4726        44     993
47       48  Facebook     video    3/22/2023 3:15   5000       232      16
57       58  Facebook     video   12/27/2023 4:00   2204       116     728
61       62  Facebook  carousel   1/27/2023 15:45   3742       227     849
65       66  Facebook      text     1/3/2023 3:00   2265        39     318
66       67  Facebook  carousel    4/23/2023 8:15   2026       390     165
69       70  Facebook      text    6/12/2023 9:30   3094        86     965
71       72  Facebook  carousel    5/5/2023 16:45   1690       257     656
72       73  Facebook      text   7/18/2023 22:00   3026        11     761
74       75  Facebook     video   7/26/2023 20:15   5000       500     404
79       80  Facebook      text   6/25/2023 15:15    553       320     312
80       81  Facebook     video    1/4/2023 18:30   2642        33     413
83       84  Facebook  carousel   10/3/2023 19:00   1203       263     417
84       85  Facebook      text     7/6/2023 7:00   2566       368     304
87       88  Facebook      text    5/3/2023 12:30   3404       244      67
90       91  Facebook  carousel    9/15/2023 0:45   3956       402     462
91       92  Facebook     video   2/23/2023 17:15   1857       216     344
93       94  Facebook     image   11/27/2023 4:30   1694       207     290

     post_day sentiment_score
0    Thursday        positive
1      Sunday         neutral
8     Tuesday         neutral
12   Saturday        negative
14     Monday        positive
19   Thursday        positive
25   Thursday        negative
27  Wednesday         neutral
28   Saturday        negative
29     Friday        positive
30     Sunday        negative
35   Saturday        positive
36   Thursday         neutral
38     Sunday         neutral
46    Tuesday        negative
47  Wednesday        negative
57  Wednesday         neutral
61     Friday        negative
65    Tuesday        positive
66     Sunday        negative
69     Monday        negative
71     Friday         neutral
72    Tuesday        positive
74  Wednesday        positive
79     Sunday        positive
80  Wednesday         neutral
83    Tuesday        negative
84   Thursday         neutral
87  Wednesday        positive
90     Friday        negative
91   Thursday        positive
93     Monday        positive   data
Instagram name
    post_id   platform post_type         post_time  likes  comments  shares  \
2         3  Instagram      poll   2/21/2023 16:15   4955       408     688
5         6  Instagram  carousel    5/5/2023 20:00    256       186     211
6         7  Instagram     image   2/26/2023 11:45   1982        30     906
7         8  Instagram      text  10/28/2023 19:30   1274        45     216
16       17  Instagram      poll     7/5/2023 5:15   2872        10     736
23       24  Instagram  carousel    1/1/2023 20:00   5000        80     399
26       27  Instagram      text   10/6/2023 10:00   3161       162     137
31       32  Instagram     image    7/1/2023 14:45   4665       202     183
34       35  Instagram     image    6/6/2023 19:30   1309       201     852
39       40  Instagram  carousel    8/4/2023 12:45    447       333     845
41       42  Instagram     video   11/23/2023 2:00   4929       252     730
43       44  Instagram      text     7/6/2023 8:00   3259        50     177
45       46  Instagram      text   5/16/2023 22:15   2251       380     427
49       50  Instagram      text    7/12/2023 0:00   1551       206     127
53       54  Instagram     image    1/21/2023 1:00   4297       360     825
55       56  Instagram     image   3/13/2023 23:15   3401       190     230
56       57  Instagram     video    7/13/2023 9:15   4846       134     498
59       60  Instagram  carousel    5/19/2023 4:30   4763       332     956
60       61  Instagram     video  12/31/2023 22:30   3544       167     761
63       64  Instagram  carousel   4/19/2023 19:45    130       452     724
64       65  Instagram     image    9/20/2023 6:00   3982       314     326
67       68  Instagram     video  12/28/2023 16:45    560       486     677
70       71  Instagram     video    4/10/2023 0:00   3398       261     630
73       74  Instagram     video   4/14/2023 10:30   5000       454     744
75       76  Instagram      text   7/27/2023 19:15   2153        81     114
77       78  Instagram      poll    1/19/2023 7:15   2990        30     365
78       79  Instagram  carousel   12/13/2023 4:45   4678       189     785
81       82  Instagram  carousel  11/19/2023 12:30   4656       314     757
82       83  Instagram     video    12/6/2023 4:00   5000       173     792
86       87  Instagram      text   5/23/2023 22:30     15        70     454
89       90  Instagram      poll    3/19/2023 4:00   3195       109     243
92       93  Instagram  carousel     5/7/2023 0:30    951       432     734
94       95  Instagram      poll    3/7/2023 19:15   3005       124     517
95       96  Instagram  carousel   7/12/2023 17:45     36       294     911
98       99  Instagram      poll  12/29/2023 12:15   5000       500     204
99      100  Instagram     image    6/6/2023 21:00   4483       357      25

     post_day sentiment_score
2     Tuesday        negative
5      Friday         neutral
6      Sunday        positive
7    Saturday         neutral
16  Wednesday        positive
23     Sunday        positive
26     Friday        positive
31   Saturday        positive
34    Tuesday        negative
39     Friday        negative
41   Thursday        negative
43   Thursday        negative
45    Tuesday        positive
49  Wednesday        negative
53   Saturday        negative
55     Monday        negative
56   Thursday         neutral
59     Friday        positive
60     Sunday        negative
63  Wednesday         neutral
64  Wednesday        positive
67   Thursday        negative
70     Monday         neutral
73     Friday        positive
75   Thursday         neutral
77   Thursday        positive
78  Wednesday        positive
81     Sunday        negative
82  Wednesday        negative
86    Tuesday         neutral
89     Sunday        negative
92     Sunday        negative
94    Tuesday        positive
95  Wednesday        positive
98     Friday        positive
99    Tuesday         neutral   data
Twitter name
    post_id platform post_type         post_time  likes  comments  shares  \
3         4  Twitter     image   11/16/2023 0:45   1183        90     187
4         5  Twitter     video    5/23/2023 0:30   3499       247     286
9        10  Twitter  carousel   5/11/2023 11:00   1878       225     438
10       11  Twitter      text    12/8/2023 2:15   1446        44      52
11       12  Twitter     video    6/15/2023 3:15    304        42      89
13       14  Twitter      text   9/30/2023 10:30   1333       144     123
15       16  Twitter     image   2/10/2023 13:00   2348       154      18
17       18  Twitter      text    7/23/2023 5:45    512       123     338
18       19  Twitter      text   11/20/2023 2:00   2013       122     183
20       21  Twitter      poll     5/2/2023 6:15    559       136      55
21       22  Twitter  carousel   1/30/2023 13:30   1961        44     439
22       23  Twitter      text   10/2/2023 12:15    332       109     348
24       25  Twitter      poll    5/17/2023 0:15    898       130     480
32       33  Twitter     video   9/27/2023 19:00    119       147     240
33       34  Twitter      poll    2/9/2023 15:30   2253       162      28
37       38  Twitter      poll     5/2/2023 0:30   2463       187     445
40       41  Twitter  carousel  12/27/2023 11:30    667       176     461
42       43  Twitter  carousel   3/31/2023 16:00   2586        97      85
44       45  Twitter     video   12/1/2023 10:00   2236       132     118
48       49  Twitter     image   4/17/2023 15:00    725       169     298
50       51  Twitter      text   2/14/2023 18:00   1268        73     251
51       52  Twitter     image   7/14/2023 15:00    950       113     327
52       53  Twitter     video  11/12/2023 17:30   1498        46      96
54       55  Twitter  carousel   10/2/2023 23:30    592        34     496
58       59  Twitter     video   12/24/2023 7:45    344        99     194
62       63  Twitter     image    5/15/2023 6:30    227       163     127
68       69  Twitter     image  10/14/2023 18:45    187        89     284
76       77  Twitter  carousel    7/5/2023 18:15   3571       102      96
85       86  Twitter      text   11/25/2023 7:30   2416        50      62
88       89  Twitter  carousel     5/3/2023 8:00   2884       197     339
96       97  Twitter     video  10/27/2023 23:45    314       108     458
97       98  Twitter      text     8/5/2023 8:45    229       179      38

     post_day sentiment_score
3    Thursday        negative
4     Tuesday        positive
9    Thursday         neutral
10     Friday        negative
11   Thursday        positive
13   Saturday        positive
15     Friday         neutral
17     Sunday         neutral
18     Monday        positive
20    Tuesday         neutral
21     Monday        positive
22     Monday        positive
24  Wednesday        positive
32  Wednesday        positive
33   Thursday        positive
37    Tuesday        positive
40  Wednesday        positive
42     Friday        positive
44     Friday        positive
48     Monday         neutral
50    Tuesday        positive
51     Friday        positive
52     Sunday        positive
54     Monday         neutral
58     Sunday         neutral
62     Monday         neutral
68   Saturday         neutral
76  Wednesday        positive
85   Saturday        positive
88  Wednesday        positive
96     Friday         neutral
97   Saturday        positive   data

In [62]:
df.groupby("platform").nth(0)

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative

In [63]:
df.groupby("platform").nth(3)

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
7,8,Instagram,text,10/28/2023 19:30,1274,45,216,Saturday,neutral
10,11,Twitter,text,12/8/2023 2:15,1446,44,52,Friday,negative
12,13,Facebook,carousel,11/11/2023 15:45,45,78,375,Saturday,negative

In [64]:
df.groupby("platform").nunique()

,post_id,post_type,post_time,likes,comments,shares,post_day,sentiment_score
platform,,,,,,,,
Facebook,32,5,32,29,28,32,7,3
Instagram,36,5,36,33,34,36,7,3
Twitter,32,5,32,32,31,31,7,3

In [72]:
df.groupby("platform").agg({"likes":sum,"comments":max})

            likes  comments
platform
Facebook    86392       500
Instagram  107994       500
Twitter     43795       247